name = "Jexpresso"
uuid = "b6c1962e-2b89-11f0-398d-4f31b209be71"
version = "0.1.0"

[deps]
AMRVW = "233ec0c9-6b8d-4766-b9a2-a16e389fc38a"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Artifacts = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
ClimaComms = "3a4d1b5c-c61d-41fd-a00a-5873ba7a1b0d"
ClimaParams = "5c42b081-d73a-476f-9059-fd94b934656c"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Dierckx = "39dd38d3-220a-591b-8e3c-4c3a8c710a94"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
DiffEqDevTools = "f3b72e0c-5b89-59e1-b016-84e28bfd966d"
DifferentialEquations = "0c46a032-eb83-5123-abaf-570d42b7fbaa"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
ElasticArrays = "fdbdab4c-e67f-52f5-8c3f-e7b388dad3d4"
Geodesy = "0ef565a4-170c-5f04-8de2-149903a85f3d"
Gridap = "56d4f2e9-7ea1-5844-9cf6-b9c51ca7ce8e"
GridapDistributed = "f9701e48-63b3-45aa-9a63-9bc6c271f355"
GridapGmsh = "3025c34a-b394-11e9-2a55-3fee550c04c8"
GridapP4est = "c2c8e14b-f5fd-423d-9666-1dd9ad120af9"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Infiltrator = "5903a43b-9cc3-4c30-8d17-598619ec4e9b"
InternedStrings = "7d512f48-7fb1-5a58-b986-67e6dc259f01"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"
Krylov = "ba0b0d4f-ebba-5204-a429-3ac8c609bfb7"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LinearSolve = "7ed4a6bd-45f5-4d41-b270-4a48e9bafcae"
LoopVectorization = "bdcacae8-1622-11e9-2a5c-532679323890"
MPI = "da04e1cc-30fd-572f-bb4f-1f8673147195"
MPIPreferences = "3da0fdf6-3ccc-4f1b-acd9-58baa6c99267"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
P4est_wrapper = "3743d7c0-8adf-11ea-380b-7d33b0ecc1da"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PartitionedArrays = "5a9dfac6-5c52-46f7-8278-5e2210713be9"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Polynomials = "f27b6e38-b328-58d1-80ce-0feddd5e7a45"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
Quadmath = "be4d8f0f-7fa4-5f49-b795-2f01399ab2dd"
RRTMGP = "a01a1ee8-cea4-48fc-987c-fc7878d79da1"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SciMLBase = "0bca4576-84f4-4d90-8ffe-ffa030f20462"
SnoopCompile = "aa65fe97-06da-5843-b5b1-d5d13cad87d2"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Thermodynamics = "b60c26fb-14c3-4610-9d3e-2d17fe7ff00c"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
UnicodePlots = "b8865327-cd53-5732-bb35-84acbb429228"
WriteVTK = "64499a7a-5c06-52f2-abe2-ccb03c286192"

[compat]
julia = "1.11"
AMRVW = "0.1"
ArgParse = "1"
BenchmarkTools = "1"
CSV = "0.10.15"
ClimaComms = "0.6"
ClimaParams = "0.10"
ColorSchemes = "3"
Crayons = "=4.1.1"
DataFrames = "1"
DataStructures = "0.18"
Dierckx = "0.5"
DiffEqBase = "6"
DiffEqDevTools = "2"
DifferentialEquations = "7"
Distributions = "0.25"
DocStringExtensions = "0.9"
ElasticArrays = "1"
Geodesy = "1"
Gridap = "=0.18.12"
GridapDistributed = "=0.4.7"
GridapGmsh = "=0.7.2"
GridapP4est = "=0.3.11"
HDF5 = "0.17"
Infiltrator = "1"
InternedStrings = "0.7"
KernelAbstractions = "0.9"
Krylov = "0.9"
LaTeXStrings = "1"
LinearSolve = "2"
LoopVectorization = "0.12"
MPI = "=0.20.22"
MPIPreferences = "=0.1.11"
NCDatasets = "0.14"
OrdinaryDiffEq = "6"
P4est_wrapper = "0.2"
Parameters = "0.12"
PartitionedArrays = "0.3"
Plots = "1"
Polynomials = "4"
PrettyTables = "=2.4.0"
Quadmath = "0.5"
RRTMGP = "0.19"
Revise = "3"
Roots = "2.2.10"
SciMLBase = "2"
SnoopCompile = "2"
SpecialFunctions = "2"
StaticArrays = "1"
Thermodynamics = "=0.12.7"
TimerOutputs = "0.5"
UnicodePlots = "=3.7.2"
WriteVTK = "1"
